twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /vehicle/ackermann_cmd_vel
        timeout : 0.5
        priority: 10
      joystick:
        topic   : /vehicle/rc_cmd_vel
        timeout : 0.5
        priority: 100